### ISSUE TITLE
Will Agora Work in Home Networks Without Router Configurations (Port Forwarding, Reverse DNS)?

### ISSUE THREAD

**Issue by moresearch** [agora-protocol/paper-demo#3]
Will Agora work seamlessly in home networks without requiring router configurations (e.g., port forwarding, reverse DNS), and how does it handle NAT and firewalls for effective communication?

**Comment by samuelemarro** [comment]
Hi @moresearch,
Yes, Agora uses regular HTTP queries and non-reserved ports, so routers shouldn't be a problem.
